timeonload: true
debug: false
showUpdateMessage: true
timezoneOverwrite: false
timezoneOverwriteValue: 'GMT'
language: 'en'
database:
  enabled: false
  url: 'jdbc:mysql://localhost:3306/commandtimer'
  username: 'root'
  password: ''